# Generated by Django 3.0.5 on 2020-08-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
